import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zipSync, strToU8 } from 'fflate';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, '..');
const out = resolve(root, 'e2e/fixtures');
mkdirSync(out, { recursive: true });

const bath = readFileSync(resolve(root, 'test/fixtures/reference-bath.csv'));
const sonar = readFileSync(resolve(root, 'test/fixtures/reference-sonar.csv'));
const zipped = zipSync({
  'bathymetry.csv': new Uint8Array(bath),
  'sonar.csv': new Uint8Array(sonar),
  README: strToU8('Generated by scripts/build-e2e-fixture.ts'),
});
writeFileSync(resolve(out, 'synthetic.zip'), zipped);
console.log('wrote', resolve(out, 'synthetic.zip'), zipped.length, 'bytes');
